name: Feature Request
description: Suggest a new feature or enhancement for dot
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem or limitation are you trying to solve? What use case is currently unsupported?
      placeholder: Describe the problem or gap in functionality...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working? What would the user experience look like?
      placeholder: |
        Describe your proposed solution, including:
        - Command line interface (if applicable)
        - Expected behavior
        - Example usage
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternative approaches you've thought about...

  - type: textarea
    id: api-design
    attributes:
      label: API Design (if applicable)
      description: If this feature affects the library interface, describe the proposed API
      placeholder: |
        ```rust
        // Example API design
        ```

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples from other tools, or screenshots about the feature request
      placeholder: Links to similar features in other dotfiles managers, implementation notes, etc.
